apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sns-backend
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: python-sns-backend
  template:
    metadata:
      labels:
        app: python-sns-backend
    spec:
      containers:
      - name: python-sns-backend
        image: public.ecr.aws/r4v6g9w1/python-sns-backend:latest
        ports:
        - containerPort: 5001 # Adjust to match the port your Flask app is running on
